NAME	= libftprintf.a

CC		= gcc

CFLAGS	= -Wall -Werror -Wextra

LIBRI	= ft_printf.h

SRCS	=  ft_printf.c ft_uns_itoa.c ft_printf_utils.c ft_printf_utils_b.c 	ft_printf_utils_c.c ft_printf_utils_d.c ft_printf_utils_e.c ft_printf_utils_f.c ft_printf_utils_g.c

OBJS	= ${SRCS:.c=.o}

RM		= rm -f


$(NAME): ${OBJS}
		ar -rcs ${NAME} ${OBJS}

all:	${NAME}

.c.o:
		${CC} ${CFLAGS} -I ${LIBRI} -c $< -o ${<:.c=.o}

clean:
		${RM} ${OBJS} *.gch

fclean:	clean
		${RM} ${NAME}

re:	fclean all

